---

- hosts: redhat
  become: yes
  remote_user: sysadmin
  
  tasks:
  - name: Instalador de PODMAN
    yum:
      name: podman
      state: present
    notify: Restart server

  - name: Habilitación e inicio del servicio
    service:
      name: podman
      state: started
      enabled: true  

  handlers:
  - name: Restart server
    reboot:
