---

- hosts: tester
  become: yes
  remote_user: sysadmin
  
  tasks:
  - name: Installing podman.
    yum:
      name: podman
      state: present
    notify: Restart server


  handlers:
  - name: Restart server
    reboot:
